use std::any::Any;
use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use dashmap::DashMap;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::error::{AgentTeamsError, Result};

/// Type-safe shared resource pool (replaces DashMap<String, Arc<dyn Any>>)
#[derive(Debug, Clone, Default)]
pub struct ResourcePool {
    resources: DashMap<String, Arc<dyn Any + Send + Sync>>,
}

impl ResourcePool {
    pub fn new() -> Self {
        Self {
            resources: DashMap::new(),
        }
    }

    /// Get a typed resource by name
    pub fn get<T: Send + Sync + 'static>(&self, name: &str) -> Option<Arc<T>> {
        self.resources
            .get(name)
            .and_then(|r| r.value().clone().downcast::<T>().ok())
    }

    /// Register a typed resource
    pub fn register<T: Send + Sync + 'static>(&self, name: &str, resource: Arc<T>) {
        self.resources.insert(name.to_string(), resource);
    }

    /// Remove a resource
    pub fn remove(&self, name: &str) -> Option<Arc<dyn Any + Send + Sync>> {
        self.resources.remove(name).map(|(_, v)| v)
    }

    /// Check if a resource exists
    pub fn contains(&self, name: &str) -> bool {
        self.resources.contains_key(name)
    }
}

/// Standardized Tool definition (compatible with OpenAI Functions / Anthropic Tools / MCP)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tool {
    pub name: String,
    pub description: String,
    pub parameters: ToolParameters,
    /// Tool type: "function" (default, locally executed) or platform tools like "web_search".
    /// Non-function tools are included in LLM requests but not executed locally.
    #[serde(default = "default_tool_type")]
    pub tool_type: String,
    /// Executor ID for routing to concrete implementation
    pub executor_id: String,
    /// Permission tags for policy control
    pub permission_tags: Vec<String>,
    /// Whether parallel invocation is allowed
    pub allow_parallel: bool,
    /// Default timeout in milliseconds
    pub default_timeout_ms: u64,
    /// Human-readable data flow hints for the LLM.
    /// Describes what kind of input this tool expects and what it outputs,
    /// helping the LLM plan multi-step tool chains.
    /// Example: "需要文件路径作为输入，可先用 file(write) 写入上下文数据"
    #[serde(default)]
    pub data_flow_hints: Vec<String>,
    /// Names of tools that should typically be called before this one.
    /// Used by the LLM to understand prerequisite steps.
    #[serde(default)]
    pub prerequisites: Vec<String>,
    /// Describes the output fields this tool produces on success.
    /// Helps the LLM know what data is available for chaining to the next tool.
    /// Format: "field_name: description"
    /// Example: ["path: 写入的文件路径", "bytes_written: 写入字节数"]
    #[serde(default)]
    pub output_fields: Vec<String>,
}

fn default_tool_type() -> String {
    "function".to_string()
}

/// Tool parameter schema
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolParameters {
    pub schema: Value, // JSON Schema
    pub required: Vec<String>,
}

/// Tool call request (generated by LLM or constructed programmatically)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    pub id: String,
    pub name: String,
    pub arguments: Value,
}

/// Tool call result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResult {
    pub call_id: String,
    pub name: String,
    pub success: bool,
    pub output: Value,
    pub error: Option<String>,
    pub execution_duration_ms: u64,
}

impl ToolResult {
    /// Compact representation for LLM context — strips verbose fields, truncates large output.
    /// Saves tokens when tool results are passed back as message history.
    /// Includes data flow hints to help the LLM chain tools effectively.
    pub fn compact(&self) -> Value {
        if self.success {
            // Directly clone the Value — avoid to_string() + from_str() roundtrip
            let output = if self.output.is_null() {
                Value::Null
            } else {
                let s = self.output.to_string();
                if s.len() > 16000 {
                    let mut end = 16000;
                    while end > 0 && !s.is_char_boundary(end) {
                        end -= 1;
                    }
                    Value::String(format!("{}...(truncated, {} chars total)", &s[..end], s.len()))
                } else {
                    self.output.clone()
                }
            };

            // Add data flow hints based on tool name
            let hint = match self.name.as_str() {
                "file" => {
                    if let Some(out) = self.output.as_object() {
                        if out.get("path").is_some() {
                            Some("文件已写入，path 可作为其它工具的输入参数")
                        } else if out.get("content").is_some() {
                            Some("文件内容已读取，可用于构造其它工具的参数")
                        } else {
                            None
                        }
                    } else {
                        None
                    }
                }
                _ => None,
            };

            // List output keys available for chaining to the next tool
            let chaining_keys: Vec<String> = match &self.output {
                Value::Object(map) => map.keys().cloned().collect(),
                _ => vec![],
            };

            let mut result = serde_json::json!({
                "tool": self.name,
                "ok": true,
                "output": output,
                "ms": self.execution_duration_ms,
            });
            if let Some(h) = hint {
                result["hint"] = Value::String(h.to_string());
            }
            if !chaining_keys.is_empty() {
                result["chaining_keys"] = Value::Array(
                    chaining_keys.into_iter().map(Value::String).collect()
                );
            }
            result
        } else {
            serde_json::json!({
                "tool": self.name,
                "ok": false,
                "error": self.error.as_deref().unwrap_or("unknown"),
                "ms": self.execution_duration_ms,
            })
        }
    }
}

/// Build a structured error ToolResult that gives the Agent enough information to self-correct.
///
/// Fields in the output:
/// - `success`: false
/// - `error`: human-readable error message
/// - `details`: technical details (OS error kind, path, etc.)
/// - `suggestion`: what the Agent should try next
/// - `tool`: tool name for context
pub fn tool_error(
    call: &ToolCall,
    error: impl Into<String>,
    details: impl Into<String>,
    suggestion: impl Into<String>,
    duration_ms: u64,
) -> ToolResult {
    let error = error.into();
    let details = details.into();
    let suggestion = suggestion.into();

    tracing::error!(
        tool = %call.name,
        call_id = %call.id,
        error = %error,
        details = %details,
        "Tool execution failed"
    );

    ToolResult {
        call_id: call.id.clone(),
        name: call.name.clone(),
        success: false,
        output: serde_json::json!({
            "success": false,
            "error": error,
            "details": details,
            "suggestion": suggestion,
            "tool": call.name,
        }),
        error: Some(error),
        execution_duration_ms: duration_ms,
    }
}

/// Build a success ToolResult with tracing.
pub fn tool_success(
    call: &ToolCall,
    output: serde_json::Value,
    duration_ms: u64,
) -> ToolResult {
    tracing::debug!(
        tool = %call.name,
        call_id = %call.id,
        duration_ms = duration_ms,
        "Tool execution succeeded"
    );

    ToolResult {
        call_id: call.id.clone(),
        name: call.name.clone(),
        success: true,
        output,
        error: None,
        execution_duration_ms: duration_ms,
    }
}

/// Incremental tool call delta (for streaming)
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct ToolCallDelta {
    pub index: usize,
    pub id: Option<String>,
    pub name: Option<String>,
    pub arguments_delta: Option<String>,
}

/// Tool execution status — real-time progress events streamed to the frontend
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(tag = "status")]
pub enum ToolStatusEvent {
    /// Tool call is being prepared
    #[serde(rename = "preparing")]
    Preparing {
        call_id: String,
        tool_name: String,
        #[schema(value_type = Object)]
        arguments: Value,
    },
    /// Tool is executing
    #[serde(rename = "executing")]
    Executing {
        call_id: String,
        tool_name: String,
    },
    /// Tool completed successfully
    #[serde(rename = "completed")]
    Completed {
        call_id: String,
        tool_name: String,
        success: bool,
        #[schema(value_type = Object)]
        output: Value,
        error: Option<String>,
        duration_ms: u64,
    },
    /// Tool requires human approval before execution
    #[serde(rename = "approval_required")]
    ApprovalRequired {
        call_id: String,
        tool_name: String,
        #[schema(value_type = Object)]
        arguments: Value,
        approval_message: String,
    },
    /// Tool was approved and is now executing
    #[serde(rename = "approved")]
    Approved {
        call_id: String,
        tool_name: String,
    },
    /// Tool was rejected by the user
    #[serde(rename = "rejected")]
    Rejected {
        call_id: String,
        tool_name: String,
        reason: Option<String>,
    },
    /// Tool execution failed with error
    #[serde(rename = "error")]
    Error {
        call_id: String,
        tool_name: String,
        error: String,
    },
}

/// Tool execution context
#[derive(Debug, Clone)]
pub struct ToolExecutionContext {
    pub session_id: String,
    pub user_id: Option<String>,
    pub agent_id: String,
    pub request_id: String,
    /// Tool call history in the current turn
    pub tool_history: Vec<(ToolCall, ToolResult)>,
    /// Type-safe shared resource pool (replaces DashMap<String, Arc<dyn Any>>)
    pub resources: Arc<ResourcePool>,
    /// Agent context cache — injected directly from the agent pipeline.
    /// Tools can access working memory, system instructions, conversation history,
    /// and domain state without needing separate cache lookups.
    pub agent_context: Option<Arc<crate::context::AgentContext>>,
}

impl ToolExecutionContext {
    /// Create a minimal context without agent context (for standalone tool calls)
    pub fn minimal(session_id: impl Into<String>, agent_id: impl Into<String>) -> Self {
        Self {
            session_id: session_id.into(),
            user_id: None,
            agent_id: agent_id.into(),
            request_id: uuid::Uuid::new_v4().to_string(),
            tool_history: vec![],
            resources: Arc::new(ResourcePool::new()),
            agent_context: None,
        }
    }

    /// Create a context with agent context injected (for pipeline tool calls)
    pub fn with_agent_context(
        session_id: impl Into<String>,
        agent_id: impl Into<String>,
        agent_ctx: Arc<crate::context::AgentContext>,
    ) -> Self {
        let session = session_id.into();
        Self {
            session_id: session.clone(),
            user_id: agent_ctx.user_id.clone(),
            agent_id: agent_id.into(),
            request_id: uuid::Uuid::new_v4().to_string(),
            tool_history: vec![],
            resources: Arc::new(ResourcePool::new()),
            agent_context: Some(agent_ctx),
        }
    }

    /// Get working memory from agent context (if available)
    pub fn working_memory(&self) -> &[crate::memory::MemoryEntry] {
        self.agent_context
            .as_ref()
            .map(|ctx| ctx.working_memory.as_slice())
            .unwrap_or(&[])
    }

    /// Get system instructions from agent context (if available)
    pub fn system_instructions(&self) -> &[String] {
        self.agent_context
            .as_ref()
            .map(|ctx| ctx.system_instructions.as_slice())
            .unwrap_or(&[])
    }

    /// Get recent conversation history from agent context (if available)
    pub fn recent_history(&self) -> &[serde_json::Value] {
        self.agent_context
            .as_ref()
            .map(|ctx| ctx.recent_history.as_slice())
            .unwrap_or(&[])
    }

    /// Get domain state from agent context (if available)
    pub fn domain_state(&self) -> Option<&serde_json::Value> {
        self.agent_context
            .as_ref()
            .map(|ctx| ctx.domain_state.as_ref())
    }

    /// Get user entity info from agent context (if available)
    pub fn entity(&self) -> Option<&serde_json::Value> {
        self.agent_context
            .as_ref()
            .and_then(|ctx| ctx.entity.as_ref())
    }

    /// Build a memory-enriched context string for tool prompts.
    /// Combines working memory, system instructions, and recent history into
    /// a single injectable string that tools can embed in their prompts.
    pub fn build_context_injection(&self) -> String {
        let mut parts = Vec::new();

        // Working memory (user profile, facts, summaries)
        if let Some(ctx) = &self.agent_context {
            let memory_prompt = ctx.build_memory_prompt();
            if !memory_prompt.is_empty() {
                parts.push(memory_prompt);
            }
        }

        // System instructions
        let instructions = self.system_instructions();
        if !instructions.is_empty() {
            parts.push(format!(
                "## 系统指令\n{}",
                instructions.join("\n")
            ));
        }

        // Recent history (last 5 turns, compact)
        let history = self.recent_history();
        if !history.is_empty() {
            let recent: Vec<String> = history
                .iter()
                .rev()
                .take(5)
                .map(|v| {
                    let s = v.to_string();
                    if s.len() > 500 {
                        let mut end = 500;
                        while end > 0 && !s.is_char_boundary(end) {
                            end -= 1;
                        }
                        format!("{}...", &s[..end])
                    } else {
                        s
                    }
                })
                .collect();
            parts.push(format!(
                "## 最近对话\n{}",
                recent.join("\n")
            ));
        }

        parts.join("\n\n")
    }
}

/// Tool executor trait (plugin-based)
#[async_trait]
pub trait ToolExecutor: Send + Sync {
    fn executor_id(&self) -> &str;

    /// Execute a tool call
    async fn execute(&self, call: &ToolCall, ctx: &ToolExecutionContext) -> Result<ToolResult>;

    /// Health check
    async fn health_check(&self) -> bool {
        true
    }

    /// List all tools provided by this executor
    fn list_tools(&self) -> Vec<Tool>;
}

/// Retry policy for tool execution
#[derive(Clone, Debug)]
pub struct RetryPolicy {
    pub max_retries: u32,
    pub base_delay_ms: u64,
    pub max_delay_ms: u64,
    pub retryable_errors: Vec<String>,
}

impl Default for RetryPolicy {
    fn default() -> Self {
        Self {
            max_retries: 3,
            base_delay_ms: 100,
            max_delay_ms: 5000,
            retryable_errors: vec!["timeout".to_string(), "5xx".to_string()],
        }
    }
}

/// Tool permission policy rule
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolPolicyRule {
    /// Tool name pattern (supports wildcards)
    pub tool_pattern: String,
    /// Required permission tags
    pub required_permissions: Vec<String>,
    /// Allowed agent IDs
    pub allowed_agents: Option<Vec<String>>,
    /// Allowed user IDs
    pub allowed_users: Option<Vec<String>>,
    /// Max calls per minute
    pub rate_limit: Option<u32>,
    /// Whether human approval is required (blocks execution until approved)
    pub requires_approval: bool,
}

/// Tool permission policy engine
pub struct ToolPolicyEngine {
    pub rules: Vec<ToolPolicyRule>,
    /// Rate limit tracking: "rule_index:tool_name" -> timestamps of recent calls
    rate_limit_state: Arc<DashMap<String, Vec<std::time::Instant>>>,
}

impl std::fmt::Debug for ToolPolicyEngine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ToolPolicyEngine")
            .field("rules", &self.rules)
            .finish()
    }
}

impl Clone for ToolPolicyEngine {
    fn clone(&self) -> Self {
        Self {
            rules: self.rules.clone(),
            rate_limit_state: self.rate_limit_state.clone(),
        }
    }
}

impl Default for ToolPolicyEngine {
    fn default() -> Self {
        Self {
            rules: Vec::new(),
            rate_limit_state: Arc::new(DashMap::new()),
        }
    }
}

impl ToolPolicyEngine {
    pub fn check_permission(&self, ctx: &ToolExecutionContext, call: &ToolCall) -> Result<()> {
        match self.check_permission_inner(ctx, call, false)? {
            PermissionDecision::Allowed => Ok(()),
            PermissionDecision::PendingApproval { message } => {
                Err(AgentTeamsError::ToolNotFound(message))
            }
        }
    }

    fn match_pattern(pattern: &str, name: &str) -> bool {
        if pattern == "*" {
            return true;
        }
        if let Some(prefix) = pattern.strip_suffix('*') {
            return name.starts_with(prefix);
        }
        pattern == name
    }

    /// Check if a tool requires human approval
    pub fn requires_approval(&self, tool_name: &str) -> bool {
        self.rules.iter().any(|rule| {
            Self::match_pattern(&rule.tool_pattern, tool_name) && rule.requires_approval
        })
    }

    /// Check permission with approval-aware semantics.
    /// Returns Ok(Pending) if approval is needed, Ok(Allowed) if permitted, Err if denied.
    pub fn check_permission_with_approval(
        &self,
        ctx: &ToolExecutionContext,
        call: &ToolCall,
        skip_approval: bool,
    ) -> Result<PermissionDecision> {
        self.check_permission_inner(ctx, call, skip_approval)
    }

    /// Shared permission check logic used by both check_permission and check_permission_with_approval.
    /// First matching rule wins — if no rule matches, the tool is allowed by default.
    fn check_permission_inner(
        &self,
        ctx: &ToolExecutionContext,
        call: &ToolCall,
        skip_approval: bool,
    ) -> Result<PermissionDecision> {
        for (i, rule) in self.rules.iter().enumerate() {
            if !Self::match_pattern(&rule.tool_pattern, &call.name) {
                continue;
            }

            // First matching rule wins — check agent permission
            if let Some(ref agents) = rule.allowed_agents {
                if !agents.contains(&ctx.agent_id) {
                    return Err(AgentTeamsError::ToolNotFound(format!(
                        "Permission denied: agent '{}' not allowed to call tool '{}'",
                        ctx.agent_id, call.name
                    )));
                }
            }

            // Check user permission
            if let Some(ref users) = rule.allowed_users {
                if let Some(ref uid) = ctx.user_id {
                    if !users.contains(uid) {
                        return Err(AgentTeamsError::ToolNotFound(format!(
                            "Permission denied: user '{}' not allowed to call tool '{}'",
                            uid, call.name
                        )));
                    }
                }
            }

            // Check rate limit
            if let Some(limit) = rule.rate_limit {
                let key = format!("{}:{}", i, call.name);
                let now = std::time::Instant::now();
                let one_minute = std::time::Duration::from_secs(60);

                let mut entry = self.rate_limit_state.entry(key).or_default();
                entry.retain(|t| now.saturating_duration_since(*t) < one_minute);

                if entry.len() as u32 >= limit {
                    return Err(AgentTeamsError::ToolNotFound(format!(
                        "Rate limit exceeded for tool '{}' ({} calls/min)",
                        call.name, limit
                    )));
                }
                entry.push(now);
            }

            // Check approval requirement
            if rule.requires_approval && !skip_approval {
                return Ok(PermissionDecision::PendingApproval {
                    message: format!(
                        "Tool '{}' requires human approval before execution",
                        call.name
                    ),
                });
            }

            // First matching rule processed — stop here
            break;
        }
        Ok(PermissionDecision::Allowed)
    }

    /// Clean up rate limit state for a removed tool.
    /// Call this when a tool is unregistered to prevent memory leaks.
    pub fn cleanup_tool(&self, tool_name: &str) {
        self.rate_limit_state.retain(|key, _| {
            // Keys are "rule_index:tool_name" — remove entries matching this tool
            !key.ends_with(&format!(":{}", tool_name))
        });
    }
}

/// Permission check result
#[derive(Debug, Clone)]
pub enum PermissionDecision {
    /// Tool call is allowed
    Allowed,
    /// Tool call requires human approval
    PendingApproval { message: String },
}

/// Unified Tool Registry — global tool registration center
pub struct UnifiedToolRegistry {
    tools: DashMap<String, Tool>,
    executors: DashMap<String, Arc<dyn ToolExecutor>>,
    policy_engine: ToolPolicyEngine,
    /// Tool category index for fast retrieval
    category_index: DashMap<String, Vec<String>>,
    /// Tool dependency graph (tool_name -> depends_on)
    dependency_graph: DashMap<String, Vec<String>>,
}

impl UnifiedToolRegistry {
    pub fn new() -> Self {
        Self {
            tools: DashMap::new(),
            executors: DashMap::new(),
            policy_engine: ToolPolicyEngine::default(),
            category_index: DashMap::new(),
            dependency_graph: DashMap::new(),
        }
    }

    /// Register an executor and auto-register its tools
    pub fn register_executor(&self, executor: Arc<dyn ToolExecutor>) {
        let id = executor.executor_id().to_string();
        tracing::info!("Registering tool executor: {}", id);
        self.executors.insert(id.clone(), executor.clone());

        for tool in executor.list_tools() {
            self.tools.insert(tool.name.clone(), tool);
        }
    }

    /// Get tool definition
    pub fn get_tool(&self, name: &str) -> Option<Tool> {
        self.tools.get(name).map(|t| t.clone())
    }

    /// List all available tools
    pub fn list_tools(&self) -> Vec<Tool> {
        self.tools.iter().map(|t| t.value().clone()).collect()
    }

    /// List tools by category
    pub fn list_by_category(&self, category: &str) -> Vec<Tool> {
        if let Some(names) = self.category_index.get(category) {
            names
                .iter()
                .filter_map(|name| self.get_tool(name))
                .collect()
        } else {
            Vec::new()
        }
    }

    /// Register a tool with optional category
    pub fn register_tool(&self, tool: Tool, category: Option<&str>) {
        if let Some(cat) = category {
            self.category_index
                .entry(cat.to_string())
                .or_default()
                .push(tool.name.clone());
        }
        self.tools.insert(tool.name.clone(), tool);
    }

    /// Unregister a tool and clean up associated state (rate limits, etc.)
    pub fn unregister(&self, tool_name: &str) -> Option<Tool> {
        // Remove from category index
        for mut entry in self.category_index.iter_mut() {
            entry.value_mut().retain(|n| n != tool_name);
        }
        // Remove from dependency graph
        self.dependency_graph.remove(tool_name);
        // Clean up rate limit state
        self.policy_engine.cleanup_tool(tool_name);
        self.tools.remove(tool_name).map(|(_, t)| t)
    }

    /// Set dependencies for a tool
    pub fn set_dependencies(&self, tool_name: &str, depends_on: Vec<String>) {
        self.dependency_graph
            .insert(tool_name.to_string(), depends_on);
    }

    /// Get dependencies for a tool
    pub fn get_dependencies(&self, tool_name: &str) -> Vec<String> {
        self.dependency_graph
            .get(tool_name)
            .map(|d| d.value().clone())
            .unwrap_or_default()
    }

    /// Execute a tool call (with permission check and timeout)
    pub async fn execute(&self, call: &ToolCall, ctx: &ToolExecutionContext) -> Result<ToolResult> {
        self.policy_engine.check_permission(ctx, call)?;
        self.execute_core(call, ctx, None).await
    }

    /// Execute a tool call with real-time status events.
    /// The `event_sink` receives ToolStatusEvent as the execution progresses.
    /// If `skip_approval` is true, bypasses human approval requirements.
    pub async fn execute_with_events(
        &self,
        call: &ToolCall,
        ctx: &ToolExecutionContext,
        skip_approval: bool,
        event_sink: Option<&tokio::sync::mpsc::UnboundedSender<ToolStatusEvent>>,
    ) -> Result<ToolResult> {
        // Permission check with approval awareness
        let decision = self
            .policy_engine
            .check_permission_with_approval(ctx, call, skip_approval)?;

        match decision {
            PermissionDecision::PendingApproval { message } => {
                if let Some(sink) = event_sink {
                    let _ = sink.send(ToolStatusEvent::ApprovalRequired {
                        call_id: call.id.clone(),
                        tool_name: call.name.clone(),
                        arguments: call.arguments.clone(),
                        approval_message: message.clone(),
                    });
                }
                return Err(AgentTeamsError::ToolPendingApproval {
                    tool_name: call.name.clone(),
                    message,
                });
            }
            PermissionDecision::Allowed => {}
        }

        if let Some(sink) = event_sink {
            let _ = sink.send(ToolStatusEvent::Preparing {
                call_id: call.id.clone(),
                tool_name: call.name.clone(),
                arguments: call.arguments.clone(),
            });
        }

        let result = self.execute_core(call, ctx, event_sink).await;

        match &result {
            Ok(tool_result) => {
                if let Some(sink) = event_sink {
                    let _ = sink.send(ToolStatusEvent::Completed {
                        call_id: tool_result.call_id.clone(),
                        tool_name: tool_result.name.clone(),
                        success: tool_result.success,
                        output: tool_result.output.clone(),
                        error: tool_result.error.clone(),
                        duration_ms: tool_result.execution_duration_ms,
                    });
                }
            }
            Err(e) => {
                if let Some(sink) = event_sink {
                    let _ = sink.send(ToolStatusEvent::Error {
                        call_id: call.id.clone(),
                        tool_name: call.name.clone(),
                        error: e.to_string(),
                    });
                }
            }
        }

        result
    }

    /// Core execution logic shared by execute() and execute_with_events().
    /// Resolves tool -> executor, emits executing event, runs with timeout.
    async fn execute_core(
        &self,
        call: &ToolCall,
        ctx: &ToolExecutionContext,
        event_sink: Option<&tokio::sync::mpsc::UnboundedSender<ToolStatusEvent>>,
    ) -> Result<ToolResult> {
        let tool = self.get_tool(&call.name).ok_or_else(|| {
            AgentTeamsError::ToolNotFound(call.name.clone())
        })?;

        tracing::debug!("Executing tool '{}', executor_id='{}'", call.name, tool.executor_id);

        let executor = self.executors.get(&tool.executor_id).ok_or_else(|| {
            AgentTeamsError::ToolNotFound(format!("Executor not found: {}", tool.executor_id))
        })?;

        if let Some(sink) = event_sink {
            let _ = sink.send(ToolStatusEvent::Executing {
                call_id: call.id.clone(),
                tool_name: call.name.clone(),
            });
        }

        let timeout = Duration::from_millis(tool.default_timeout_ms);
        let result = tokio::time::timeout(timeout, executor.execute(call, ctx)).await;

        match result {
            Ok(Ok(tool_result)) => Ok(tool_result),
            Ok(Err(e)) => Err(e),
            // Return Err rather than Ok(success=false) so the retry layer
            // (execute_with_retry_core) can retry transient slowdowns and
            // the circuit breaker records the failure. Previously a timeout
            // was silently swallowed — never retried, never tripped the CB.
            Err(_) => Err(AgentTeamsError::ToolTimeout {
                tool_name: call.name.clone(),
                timeout_ms: tool.default_timeout_ms,
            }),
        }
    }

    /// Get reference to policy engine
    pub fn policy_engine(&self) -> &ToolPolicyEngine {
        &self.policy_engine
    }

    /// Get mutable reference to policy engine
    pub fn policy_engine_mut(&mut self) -> &mut ToolPolicyEngine {
        &mut self.policy_engine
    }
}

/// External tool source for dynamic tool registration
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ExternalToolSource {
    /// MCP Server configuration
    #[serde(rename = "mcp")]
    Mcp {
        endpoint: String,
        #[serde(default)]
        transport: McpTransport,
    },
    /// OpenAPI document URL
    #[serde(rename = "openapi")]
    OpenApi {
        url: String,
        auth: Option<OpenApiAuth>,
    },
}

/// MCP transport type
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum McpTransport {
    #[default]
    Sse,
    Stdio,
}

/// OpenAPI authentication
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OpenApiAuth {
    #[serde(rename = "bearer")]
    Bearer { token: String },
    #[serde(rename = "api_key")]
    ApiKey { header: String, value: String },
}

impl Default for UnifiedToolRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Builder for constructing Tool definitions ergonomically.
///
/// # Example
/// ```ignore
/// let tool = ToolBuilder::new("get_weather")
///     .description("Get current weather for a city")
///     .param_string("city", "City name", true)
///     .param_enum("unit", "Temperature unit", &["celsius", "fahrenheit"], false)
///     .executor("http")
///     .tag("network")
///     .timeout(10_000)
///     .build();
/// ```
pub struct ToolBuilder {
    name: String,
    description: String,
    properties: serde_json::Map<String, Value>,
    required: Vec<String>,
    tool_type: String,
    executor_id: String,
    permission_tags: Vec<String>,
    allow_parallel: bool,
    default_timeout_ms: u64,
    data_flow_hints: Vec<String>,
    prerequisites: Vec<String>,
    output_fields: Vec<String>,
}

impl ToolBuilder {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: String::new(),
            properties: serde_json::Map::new(),
            required: Vec::new(),
            tool_type: "function".to_string(),
            executor_id: String::new(),
            permission_tags: Vec::new(),
            allow_parallel: true,
            default_timeout_ms: 30_000,
            data_flow_hints: Vec::new(),
            prerequisites: Vec::new(),
            output_fields: Vec::new(),
        }
    }

    pub fn description(mut self, desc: impl Into<String>) -> Self {
        self.description = desc.into();
        self
    }

    pub fn executor(mut self, id: impl Into<String>) -> Self {
        self.executor_id = id.into();
        self
    }

    /// Set the tool type (e.g., "function", "web_search").
    /// Non-function tools are platform-level and not executed locally.
    pub fn tool_type(mut self, tt: impl Into<String>) -> Self {
        self.tool_type = tt.into();
        self
    }

    pub fn tag(mut self, tag: impl Into<String>) -> Self {
        self.permission_tags.push(tag.into());
        self
    }

    pub fn allow_parallel(mut self, allow: bool) -> Self {
        self.allow_parallel = allow;
        self
    }

    pub fn timeout(mut self, ms: u64) -> Self {
        self.default_timeout_ms = ms;
        self
    }

    /// Add a data flow hint describing what kind of input this tool expects
    /// and what it outputs. Helps the LLM plan multi-step tool chains.
    pub fn data_flow(mut self, hint: impl Into<String>) -> Self {
        self.data_flow_hints.push(hint.into());
        self
    }

    /// Declare a prerequisite tool that should typically be called before this one.
    pub fn requires(mut self, tool_name: impl Into<String>) -> Self {
        self.prerequisites.push(tool_name.into());
        self
    }

    /// Declare an output field this tool produces. Helps the LLM chain tools.
    /// Format: "field_name: description"
    pub fn output_field(mut self, field: impl Into<String>) -> Self {
        self.output_fields.push(field.into());
        self
    }

    /// Add a string parameter.
    pub fn param_string(self, name: impl Into<String>, desc: impl Into<String>, required: bool) -> Self {
        self.add_param(name, desc, "string", required, None, None)
    }

    /// Add an integer parameter.
    pub fn param_integer(self, name: impl Into<String>, desc: impl Into<String>, required: bool) -> Self {
        self.add_param(name, desc, "integer", required, None, None)
    }

    /// Add a number (float) parameter.
    pub fn param_number(self, name: impl Into<String>, desc: impl Into<String>, required: bool) -> Self {
        self.add_param(name, desc, "number", required, None, None)
    }

    /// Add a boolean parameter.
    pub fn param_bool(self, name: impl Into<String>, desc: impl Into<String>, required: bool) -> Self {
        self.add_param(name, desc, "boolean", required, None, None)
    }

    /// Add an object parameter.
    pub fn param_object(self, name: impl Into<String>, desc: impl Into<String>, required: bool) -> Self {
        self.add_param(name, desc, "object", required, None, None)
    }

    /// Add an array parameter.
    pub fn param_array(self, name: impl Into<String>, desc: impl Into<String>, required: bool) -> Self {
        self.add_param(name, desc, "array", required, None, None)
    }

    /// Add an enum parameter (string with allowed values).
    pub fn param_enum(
        self,
        name: impl Into<String>,
        desc: impl Into<String>,
        values: &[&str],
        required: bool,
    ) -> Self {
        self.add_param(
            name,
            desc,
            "string",
            required,
            Some(serde_json::json!(values)),
            None,
        )
    }

    /// Add a parameter with a default value.
    pub fn param_with_default(
        self,
        name: impl Into<String>,
        desc: impl Into<String>,
        json_type: impl Into<String>,
        default: Value,
    ) -> Self {
        self.add_param(name, desc, json_type, false, None, Some(default))
    }

    /// Add a raw JSON Schema property.
    pub fn param_raw(
        mut self,
        name: impl Into<String>,
        schema: Value,
        required: bool,
    ) -> Self {
        let n = name.into();
        if required {
            self.required.push(n.clone());
        }
        self.properties.insert(n, schema);
        self
    }

    fn add_param(
        mut self,
        name: impl Into<String>,
        desc: impl Into<String>,
        json_type: impl Into<String>,
        required: bool,
        enum_values: Option<Value>,
        default: Option<Value>,
    ) -> Self {
        let n = name.into();
        let mut prop = serde_json::json!({
            "type": json_type.into(),
            "description": desc.into(),
        });
        if let Some(vals) = enum_values {
            prop["enum"] = vals;
        }
        if let Some(def) = default {
            prop["default"] = def;
        }
        if required {
            self.required.push(n.clone());
        }
        self.properties.insert(n, prop);
        self
    }

    pub fn build(self) -> Tool {
        let mut schema = serde_json::json!({
            "type": "object",
            "properties": self.properties,
        });
        if !self.required.is_empty() {
            schema["required"] = serde_json::json!(self.required);
        }

        Tool {
            name: self.name,
            description: self.description,
            parameters: ToolParameters {
                schema,
                required: self.required,
            },
            tool_type: self.tool_type,
            executor_id: self.executor_id,
            permission_tags: self.permission_tags,
            allow_parallel: self.allow_parallel,
            default_timeout_ms: self.default_timeout_ms,
            data_flow_hints: self.data_flow_hints,
            prerequisites: self.prerequisites,
            output_fields: self.output_fields,
        }
    }
}

/// Declarative tool definition macro.
///
/// Generates a `Tool` struct with JSON Schema parameters from a concise DSL.
///
/// # Example
/// ```ignore
/// let weather_tool = tool!(
///     name: "get_weather",
///     description: "Get current weather for a city",
///     executor: "http",
///     tags: ["network"],
///     timeout: 10_000,
///     params: {
///         "city": (string, required, "City name"),
///         "unit": (enum ["celsius", "fahrenheit"], optional, "Temperature unit"),
///     }
/// );
/// ```
#[macro_export]
macro_rules! tool {
    (
        name: $name:expr,
        description: $desc:expr,
        executor: $exec:expr,
        tags: [$($tag:expr),* $(,)?],
        timeout: $timeout:expr,
        $(data_flow: [$($df:expr),* $(,)?],)?
        $(requires: [$($req:expr),* $(,)?],)?
        $(outputs: [$($out:expr),* $(,)?],)?
        params: {
            $( $pname:expr => ($($pdef:tt)+) ),* $(,)?
        }
    ) => {{
        let mut builder = $crate::tool::ToolBuilder::new($name)
            .description($desc)
            .executor($exec)
            .timeout($timeout);
        $( builder = builder.tag($tag); )*
        $( $( builder = builder.data_flow($df); )* )?
        $( $( builder = builder.requires($req); )* )?
        $( $( builder = builder.output_field($out); )* )*
        $( builder = $crate::tool!(@param builder, $pname, $($pdef)+); )*
        builder.build()
    }};
    // shorter form without tags/timeout
    (
        name: $name:expr,
        description: $desc:expr,
        executor: $exec:expr,
        $(data_flow: [$($df:expr),* $(,)?],)?
        $(requires: [$($req:expr),* $(,)?],)?
        $(outputs: [$($out:expr),* $(,)?],)?
        params: {
            $( $pname:expr => ($($pdef:tt)+) ),* $(,)?
        }
    ) => {{
        let mut builder = $crate::tool::ToolBuilder::new($name)
            .description($desc)
            .executor($exec);
        $( $( builder = builder.data_flow($df); )* )?
        $( $( builder = builder.requires($req); )* )?
        $( $( builder = builder.output_field($out); )* )*
        $( builder = $crate::tool!(@param builder, $pname, $($pdef)+); )*
        builder.build()
    }};

    (@param $builder:expr, $name:expr, string, required, $desc:expr) => {
        $builder.param_string($name, $desc, true)
    };
    (@param $builder:expr, $name:expr, string, optional, $desc:expr) => {
        $builder.param_string($name, $desc, false)
    };
    (@param $builder:expr, $name:expr, integer, required, $desc:expr) => {
        $builder.param_integer($name, $desc, true)
    };
    (@param $builder:expr, $name:expr, integer, optional, $desc:expr) => {
        $builder.param_integer($name, $desc, false)
    };
    (@param $builder:expr, $name:expr, number, required, $desc:expr) => {
        $builder.param_number($name, $desc, true)
    };
    (@param $builder:expr, $name:expr, number, optional, $desc:expr) => {
        $builder.param_number($name, $desc, false)
    };
    (@param $builder:expr, $name:expr, bool, required, $desc:expr) => {
        $builder.param_bool($name, $desc, true)
    };
    (@param $builder:expr, $name:expr, bool, optional, $desc:expr) => {
        $builder.param_bool($name, $desc, false)
    };
    (@param $builder:expr, $name:expr, object, required, $desc:expr) => {
        $builder.param_object($name, $desc, true)
    };
    (@param $builder:expr, $name:expr, object, optional, $desc:expr) => {
        $builder.param_object($name, $desc, false)
    };
    (@param $builder:expr, $name:expr, array, required, $desc:expr) => {
        $builder.param_array($name, $desc, true)
    };
    (@param $builder:expr, $name:expr, array, optional, $desc:expr) => {
        $builder.param_array($name, $desc, false)
    };
    (@param $builder:expr, $name:expr, enum [$($val:expr),+], required, $desc:expr) => {
        $builder.param_enum($name, $desc, &[$($val),+], true)
    };
    (@param $builder:expr, $name:expr, enum [$($val:expr),+], optional, $desc:expr) => {
        $builder.param_enum($name, $desc, &[$($val),+], false)
    };
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tool_result_compact_success() {
        let result = ToolResult {
            call_id: "c1".to_string(),
            name: "file".to_string(),
            success: true,
            output: serde_json::json!({"status": 200, "data": "hello"}),
            error: None,
            execution_duration_ms: 150,
        };
        let compact = result.compact();
        assert_eq!(compact["tool"], "file");
        assert_eq!(compact["ok"], true);
        assert_eq!(compact["ms"], 150);
        assert!(compact["output"].is_object());
        // call_id should not be in compact form
        assert!(compact.get("call_id").is_none());
    }

    #[test]
    fn test_tool_result_compact_failure() {
        let result = ToolResult {
            call_id: "c2".to_string(),
            name: "file_read".to_string(),
            success: false,
            output: Value::Null,
            error: Some("File not found".to_string()),
            execution_duration_ms: 5,
        };
        let compact = result.compact();
        assert_eq!(compact["ok"], false);
        assert_eq!(compact["error"], "File not found");
        assert!(compact.get("output").is_none());
    }

    #[test]
    fn test_tool_result_compact_truncates_large_output() {
        let large_string = "x".repeat(20000);
        let result = ToolResult {
            call_id: "c3".to_string(),
            name: "web_scrape".to_string(),
            success: true,
            output: Value::String(large_string.clone()),
            error: None,
            execution_duration_ms: 200,
        };
        let compact = result.compact();
        let output_str = compact["output"].as_str().unwrap();
        assert!(output_str.len() < large_string.len());
        assert!(output_str.contains("truncated"));
    }

    #[test]
    fn test_tool_policy_engine_match_pattern() {
        assert!(ToolPolicyEngine::match_pattern("*", "any_tool"));
        assert!(ToolPolicyEngine::match_pattern("file_*", "file_read"));
        assert!(!ToolPolicyEngine::match_pattern("file_*", "db_query"));
        assert!(ToolPolicyEngine::match_pattern("exact", "exact"));
        assert!(!ToolPolicyEngine::match_pattern("exact", "other"));
    }

    #[test]
    fn test_tool_policy_engine_check_permission() {
        let engine = ToolPolicyEngine {
            rules: vec![ToolPolicyRule {
                tool_pattern: "file_*".to_string(),
                required_permissions: vec![],
                allowed_agents: Some(vec!["tool_exec".to_string()]),
                allowed_users: None,
                rate_limit: None,
                requires_approval: false,
            }],
            ..ToolPolicyEngine::default()
        };

        let ctx = ToolExecutionContext {
            session_id: "s1".to_string(),
            user_id: None,
            agent_id: "tool_exec".to_string(),
            request_id: "r1".to_string(),
            tool_history: vec![],
            resources: Arc::new(ResourcePool::new()),
            agent_context: None,
        };

        let call = ToolCall {
            id: "c1".to_string(),
            name: "file_read".to_string(),
            arguments: Value::Null,
        };

        assert!(engine.check_permission(&ctx, &call).is_ok());

        let ctx_denied = ToolExecutionContext {
            agent_id: "knowledge".to_string(),
            ..ctx
        };
        assert!(engine.check_permission(&ctx_denied, &call).is_err());
    }

    #[test]
    fn test_unified_tool_registry_list_tools() {
        let registry = UnifiedToolRegistry::new();
        assert!(registry.list_tools().is_empty());
    }

    #[test]
    fn test_policy_engine_rate_limit() {
        let engine = ToolPolicyEngine {
            rules: vec![ToolPolicyRule {
                tool_pattern: "file_*".to_string(),
                required_permissions: vec![],
                allowed_agents: None,
                allowed_users: None,
                rate_limit: Some(2),
                requires_approval: false,
            }],
            ..ToolPolicyEngine::default()
        };

        let ctx = ToolExecutionContext {
            session_id: "s1".to_string(),
            user_id: None,
            agent_id: "tool_exec".to_string(),
            request_id: "r1".to_string(),
            tool_history: vec![],
            resources: Arc::new(ResourcePool::new()),
            agent_context: None,
        };

        let call = ToolCall {
            id: "c1".to_string(),
            name: "file_read".to_string(),
            arguments: Value::Null,
        };

        // First two calls should succeed
        assert!(engine.check_permission(&ctx, &call).is_ok());
        assert!(engine.check_permission(&ctx, &call).is_ok());
        // Third call should be rate-limited
        assert!(engine.check_permission(&ctx, &call).is_err());
    }

    #[test]
    fn test_policy_engine_requires_approval() {
        let engine = ToolPolicyEngine {
            rules: vec![ToolPolicyRule {
                tool_pattern: "*".to_string(),
                required_permissions: vec![],
                allowed_agents: None,
                allowed_users: None,
                rate_limit: None,
                requires_approval: true,
            }],
            ..ToolPolicyEngine::default()
        };

        let ctx = ToolExecutionContext {
            session_id: "s1".to_string(),
            user_id: None,
            agent_id: "tool_exec".to_string(),
            request_id: "r1".to_string(),
            tool_history: vec![],
            resources: Arc::new(ResourcePool::new()),
            agent_context: None,
        };

        let call = ToolCall {
            id: "c1".to_string(),
            name: "file_read".to_string(),
            arguments: Value::Null,
        };

        assert!(engine.check_permission(&ctx, &call).is_err());
    }

    #[test]
    fn test_policy_engine_allowed_users() {
        let engine = ToolPolicyEngine {
            rules: vec![ToolPolicyRule {
                tool_pattern: "file_*".to_string(),
                required_permissions: vec![],
                allowed_agents: None,
                allowed_users: Some(vec!["user_admin".to_string()]),
                rate_limit: None,
                requires_approval: false,
            }],
            ..ToolPolicyEngine::default()
        };

        let call = ToolCall {
            id: "c1".to_string(),
            name: "file_read".to_string(),
            arguments: Value::Null,
        };

        // Allowed user
        let ctx_ok = ToolExecutionContext {
            session_id: "s1".to_string(),
            user_id: Some("user_admin".to_string()),
            agent_id: "tool_exec".to_string(),
            request_id: "r1".to_string(),
            tool_history: vec![],
            resources: Arc::new(ResourcePool::new()),
            agent_context: None,
        };
        assert!(engine.check_permission(&ctx_ok, &call).is_ok());

        // Disallowed user
        let ctx_denied = ToolExecutionContext {
            user_id: Some("user_guest".to_string()),
            ..ctx_ok
        };
        assert!(engine.check_permission(&ctx_denied, &call).is_err());
    }

    #[test]
    fn test_policy_engine_unmatched_rule_passes() {
        let engine = ToolPolicyEngine {
            rules: vec![ToolPolicyRule {
                tool_pattern: "db_*".to_string(),
                required_permissions: vec![],
                allowed_agents: Some(vec!["admin".to_string()]),
                allowed_users: None,
                rate_limit: None,
                requires_approval: false,
            }],
            ..ToolPolicyEngine::default()
        };

        let ctx = ToolExecutionContext {
            session_id: "s1".to_string(),
            user_id: None,
            agent_id: "tool_exec".to_string(),
            request_id: "r1".to_string(),
            tool_history: vec![],
            resources: Arc::new(ResourcePool::new()),
            agent_context: None,
        };

        // file_read doesn't match db_* pattern, so it should pass
        let call = ToolCall {
            id: "c1".to_string(),
            name: "file_read".to_string(),
            arguments: Value::Null,
        };
        assert!(engine.check_permission(&ctx, &call).is_ok());
    }

    #[test]
    fn test_tool_builder() {
        let tool = ToolBuilder::new("get_weather")
            .description("Get weather for a city")
            .executor("http")
            .tag("network")
            .timeout(10_000)
            .param_string("city", "City name", true)
            .param_enum("unit", "Temperature unit", &["celsius", "fahrenheit"], false)
            .build();

        assert_eq!(tool.name, "get_weather");
        assert_eq!(tool.description, "Get weather for a city");
        assert_eq!(tool.executor_id, "http");
        assert_eq!(tool.permission_tags, vec!["network"]);
        assert_eq!(tool.default_timeout_ms, 10_000);
        assert_eq!(tool.parameters.required, vec!["city"]);
        assert!(tool.parameters.schema["properties"]["city"].is_object());
        assert!(tool.parameters.schema["properties"]["unit"]["enum"].is_array());
    }

    #[test]
    fn test_tool_macro() {
        let weather_tool = tool!(
            name: "get_weather",
            description: "Get weather",
            executor: "http",
            tags: ["network"],
            timeout: 10_000,
            params: {
                "city" => (string, required, "City name"),
                "unit" => (enum ["celsius", "fahrenheit"], optional, "Unit")
            }
        );

        assert_eq!(weather_tool.name, "get_weather");
        assert_eq!(weather_tool.executor_id, "http");
        assert_eq!(weather_tool.parameters.required, vec!["city"]);
    }

    #[test]
    fn test_tool_macro_short_form() {
        let t = tool!(
            name: "echo",
            description: "Echo back input",
            executor: "builtin",
            params: {
                "text" => (string, required, "Text to echo")
            }
        );
        assert_eq!(t.name, "echo");
        assert_eq!(t.permission_tags.len(), 0);
    }
}
